name: Docker

on:
  push:
    tags:
      - 'rel-*'

jobs:
  release:   
    runs-on: ubuntu-latest

    steps:
    - name: Checkout v2
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run quality checks
      run: yarn eslint

    - name: Run tests
      run: yarn test
      
    - name: Zip artifact
      run: zip -r release.zip .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: system
        path: ./release.zip

    - name: Checkout v3
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
