name: Release Candidate

on:
  push:
    tags:
      - 'rc-*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run quality checks
      run: yarn eslint

    - name: Run tests
      run: yarn test
      
    - name: Zip artifact
      run: zip -r release.zip .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: ./release.zip

